### ISSUE TITLE
Chrome error: Your Connection is not private

### ISSUE THREAD

**Issue by victoralexander132** [mrwnwttk/skillshare-dl#13]
Hi!
When I enter my credentials from Skillshare (email and password) in terminal and hit enter, I get the message from Chrome:
```
Your connection is not private
Attackers might be trying to steal your information from skillshare.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID
```
And the script exit because of that. Any idea about how to solve this issue?
I've tried manual login but chrome keep preventing the script from doing it's magic

**Comment by mrwnwttk** [comment]
I added the --ignore-certificate-errors parameter to ChromeDriver. Please update and see if it works now.

**Comment by victoralexander132** [comment]
Thank you so much, that worked.
